baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "acedemic"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.81.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
